import type {
  BookRecord,
  ChapterRecord,
  DraftArtifact,
  MaterialRecord,
  MessageRecord,
  ResourceRecord,
  RunRecord,
  ThreadRecord,
  TruthFileRecord,
} from "../contracts.js";

const now = "2026-03-16T09:30:00+08:00";

export interface SeedData {
  readonly books: ReadonlyArray<BookRecord>;
  readonly threads: ReadonlyArray<ThreadRecord>;
  readonly messages: ReadonlyArray<MessageRecord>;
  readonly runs: ReadonlyArray<RunRecord>;
  readonly drafts: ReadonlyArray<DraftArtifact>;
  readonly materials: ReadonlyArray<MaterialRecord>;
  readonly chapters: ReadonlyArray<ChapterRecord>;
  readonly truthFiles: ReadonlyArray<TruthFileRecord>;
  readonly resources: ReadonlyArray<ResourceRecord>;
}

export function createSeedData(): SeedData {
  return {
    books: [
      {
        id: "book_001",
        title: "吞天魔帝",
        genre: "玄幻",
        phase: "第二卷推进",
        riskTone: "danger",
        riskLabel: "第12章审计失败",
        progressLabel: "13 / 240 章",
        wordsLabel: "31.2 万字",
        currentChapter: 13,
        targetChapter: 240,
        nextAction: "先处理第12章审计，再续写第13章。",
        summary: "旧宗门复辟线已经抬头，角色与 truth 一致性都在临界点。",
        metrics: { materials: 3, truthIssues: 2, pendingDrafts: 2 },
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "book_002",
        title: "焚星录",
        genre: "玄幻",
        phase: "卷一收束",
        riskTone: "warning",
        riskLabel: "素材待确认",
        progressLabel: "8 / 180 章",
        wordsLabel: "11.8 万字",
        currentChapter: 8,
        targetChapter: 180,
        nextAction: "决定新对手的角色草案，然后刷新 materials_summary。",
        summary: "试炼终章临近，设定冲突不高，但角色对位还不够狠。",
        metrics: { materials: 1, truthIssues: 0, pendingDrafts: 1 },
        createdAt: now,
        updatedAt: now,
      },
    ],
    threads: [
      {
        threadId: "thread_global_command",
        scope: "global",
        title: "总编入口",
        lastMessageAt: now,
        archived: false,
        createdAt: now,
      },
      {
        threadId: "thread_book_001_write",
        scope: "book",
        title: "吞天魔帝 / 第13章推进",
        bookId: "book_001",
        lastRunId: "run_write_001",
        lastMessageAt: now,
        archived: false,
        createdAt: now,
      },
      {
        threadId: "thread_book_001_materials",
        scope: "book",
        title: "吞天魔帝 / 素材生成",
        bookId: "book_001",
        lastRunId: "run_material_001",
        lastMessageAt: now,
        archived: false,
        createdAt: now,
      },
      {
        threadId: "thread_book_002_materials",
        scope: "book",
        title: "焚星录 / 角色候选",
        bookId: "book_002",
        lastRunId: "run_material_002",
        lastMessageAt: now,
        archived: false,
        createdAt: now,
      },
    ],
    messages: [
      {
        messageId: "msg_001",
        threadId: "thread_book_001_write",
        role: "user",
        text: "写下一章，重点写师徒矛盾和旧宗门暗线。",
        createdAt: now,
      },
      {
        messageId: "msg_002",
        threadId: "thread_book_001_write",
        role: "assistant",
        text: "我先让 writer / auditor / reviser 串行推进，再决定是否需要人工审批。",
        createdAt: now,
      },
      {
        messageId: "msg_003",
        threadId: "thread_book_001_materials",
        role: "user",
        text: "帮我生成一个反派角色。",
        createdAt: now,
      },
      {
        messageId: "msg_004",
        threadId: "thread_book_001_materials",
        role: "assistant",
        text: "先补充几个参数，我会直接给你一张结构化角色候选卡。",
        createdAt: now,
      },
    ],
    runs: [
      {
        runId: "run_write_001",
        threadId: "thread_book_001_write",
        bookId: "book_001",
        chapterNumber: 12,
        status: "awaiting_approval",
        startedAt: now,
        currentStepId: "approval_gate",
        stepCount: 3,
        estimatedDuration: 150,
        eventCursor: 0,
        pendingApprovalId: "approval_write_001",
        lastPersistedAt: now,
        skillsLocked: {
          writer: { skillId: "chief.writer", skillVersion: "1.0.0", skillHash: "writer001aaa", source: "project" },
          auditor: { skillId: "chief.auditor", skillVersion: "1.0.0", skillHash: "auditor001aa", source: "project" },
        },
        summary: "writer 已完成，auditor 发现第12章衔接冲突，等待你决定是否继续。",
        toolPresentations: [
          {
            toolEventId: "tool_trace_001",
            runId: "run_write_001",
            toolName: "chief.worker-trace",
            toolSchemaVersion: "1.0.0",
            previewPayload: {
              chapterNumber: 12,
              progress: 72,
              checkpoints: [
                { label: "Writer", status: "completed" },
                { label: "Auditor", status: "completed" },
                { label: "Reviser", status: "awaiting_approval" },
              ],
              liveNotes: ["writer 已产出第13章草稿", "auditor 发现第12章衔接冲突", "reviser 等待你确认修订策略"],
            },
            actions: [{ actionId: "cancel_write_001", type: "cancel", label: "取消执行", confirmRequired: true, riskLevel: "medium" }],
            skillId: "chief",
            skillVersion: "1.0.0",
          },
          {
            toolEventId: "tool_approval_001",
            runId: "run_write_001",
            toolName: "chief.approval-request",
            toolSchemaVersion: "1.0.0",
            previewPayload: {
              chapterNumber: 12,
              title: "是否按修订建议继续第13章？",
              blockedBy: "第12章人物位置和阵纹触发时序存在冲突，若直接续写会扩大返工范围。",
              riskLevel: "medium",
              impact: "会更新第13章草稿和 truth 摘要",
            },
            resourceRef: {
              refId: "res_audit_001",
              type: "text",
              uri: "/api/v1/resources/res_audit_001",
            },
            actions: [
              { actionId: "approval_write_001", type: "approve", label: "批准继续" },
              { actionId: "reject_write_001", type: "reject", label: "拒绝并停止" },
              { actionId: "goto_book_001", type: "navigate", label: "查看审计详情", navigateTo: "/books/book_001" },
            ],
            skillId: "chief",
            skillVersion: "1.0.0",
          },
        ],
      },
      {
        runId: "run_material_001",
        threadId: "thread_book_001_materials",
        status: "completed",
        startedAt: now,
        endedAt: now,
        currentStepId: "completed",
        stepCount: 2,
        estimatedDuration: 25,
        eventCursor: 0,
        lastPersistedAt: now,
        skillsLocked: {
          material: { skillId: "material.generator", skillVersion: "1.0.0", skillHash: "material001a", source: "project" },
        },
        summary: "角色草案已生成，等待应用或重写。",
        toolPresentations: [
          {
            toolEventId: "tool_material_result_001",
            runId: "run_material_001",
            toolName: "material.table-result",
            toolSchemaVersion: "1.0.0",
            previewPayload: {
              draftId: "draft_character_001",
              bookId: "book_001",
            },
            actions: [
              { actionId: "apply_material_001", type: "apply", label: "应用保存", riskLevel: "medium" },
              { actionId: "regen_material_001", type: "regenerate", label: "重写生成" },
              { actionId: "edit_material_001", type: "edit", label: "编辑草案" },
              { actionId: "discard_material_001", type: "discard", label: "丢弃", confirmRequired: true, riskLevel: "medium" },
              { actionId: "goto_materials_001", type: "navigate", label: "跳转素材中心", navigateTo: "/books/book_001/materials" },
            ],
            skillId: "material",
            skillVersion: "1.0.0",
          },
        ],
      },
      {
        runId: "run_material_002",
        threadId: "thread_book_002_materials",
        status: "completed",
        startedAt: now,
        endedAt: now,
        currentStepId: "completed",
        stepCount: 2,
        estimatedDuration: 25,
        eventCursor: 0,
        lastPersistedAt: now,
        skillsLocked: {
          material: { skillId: "material.generator", skillVersion: "1.0.0", skillHash: "material002a", source: "project" },
        },
        summary: "焚星录的对手角色草案已经在 materials 线程里。",
        toolPresentations: [
          {
            toolEventId: "tool_material_result_002",
            runId: "run_material_002",
            toolName: "material.table-result",
            toolSchemaVersion: "1.0.0",
            previewPayload: {
              draftId: "draft_character_002",
              bookId: "book_002",
            },
            actions: [
              { actionId: "apply_material_002", type: "apply", label: "应用保存", riskLevel: "medium" },
              { actionId: "regen_material_002", type: "regenerate", label: "重写生成" },
              { actionId: "edit_material_002", type: "edit", label: "编辑草案" },
              { actionId: "discard_material_002", type: "discard", label: "丢弃", confirmRequired: true, riskLevel: "medium" },
              { actionId: "goto_materials_002", type: "navigate", label: "跳转素材中心", navigateTo: "/books/book_002/materials" },
            ],
            skillId: "material",
            skillVersion: "1.0.0",
          },
        ],
      },
    ],
    drafts: [
      {
        draftId: "draft_character_001",
        type: "character",
        bookId: "book_001",
        status: "draft",
        revision: 1,
        sourceThreadId: "thread_book_001_materials",
        sourceRunId: "run_material_001",
        skillRef: { skillId: "material.generator", skillVersion: "1.0.0", skillHash: "material001a", source: "project" },
        toolSchemaVersion: "1.0.0",
        preview: {
          title: "裴烬",
          archetype: "旧宗门复辟线主反派",
          fit: "能贯穿第二卷，兼容师徒冲突与法统争夺。",
          anchors: ["旧宗门", "断崖遗址", "借主角破封"],
          comparison: "比单纯力量型反派更能持续制造结构压力。",
        },
        artifactSnapshotRefs: [],
        etag: "W/\"1\"",
        createdAt: now,
        updatedAt: now,
      },
      {
        draftId: "draft_character_002",
        type: "character",
        bookId: "book_002",
        status: "draft",
        revision: 1,
        sourceThreadId: "thread_book_002_materials",
        sourceRunId: "run_material_002",
        skillRef: { skillId: "material.generator", skillVersion: "1.0.0", skillHash: "material002a", source: "project" },
        toolSchemaVersion: "1.0.0",
        preview: {
          title: "黎槿",
          archetype: "卷一末段竞争对手",
          fit: "适合在试炼终章抢资源位，逼主角踩线。",
          anchors: ["旁支试炼", "资源操盘", "卷二可延续"],
        },
        artifactSnapshotRefs: [],
        etag: "W/\"1\"",
        createdAt: now,
        updatedAt: now,
      },
    ],
    materials: [
      {
        materialId: "mat_location_001",
        bookId: "book_001",
        type: "location",
        name: "万坠断崖",
        status: "applied",
        // foreign_keys 打开后，seed 里的来源 run 也必须是真实存在的记录。
        sourceRunId: "run_write_001",
        sourceThreadId: "thread_book_001_write",
        provenance: "materials_summary.md",
        note: "卷二关键交锋地点。",
        payload: {
          title: "万坠断崖",
          description: "旧宗门残碑与断层阵纹并存的高危地点。",
        },
        createdAt: now,
        updatedAt: now,
      },
    ],
    chapters: [
      {
        bookId: "book_001",
        chapterNumber: 12,
        title: "旧钟鸣",
        status: "needs-review",
        wordCount: 4200,
        auditStatus: "failed",
        content: "第12章正文占位：这里保留成 mock 章节内容，用于 UI 与审计卡联调。",
        createdAt: now,
        updatedAt: now,
      },
      {
        bookId: "book_001",
        chapterNumber: 13,
        title: "夜入断崖",
        status: "draft",
        wordCount: 3800,
        auditStatus: "pending",
        content: "第13章正文占位：等待审批通过后会刷新状态。",
        createdAt: now,
        updatedAt: now,
      },
      {
        bookId: "book_002",
        chapterNumber: 8,
        title: "灰烬问心",
        status: "draft",
        wordCount: 3600,
        auditStatus: "pending",
        content: "焚星录第8章正文占位。",
        createdAt: now,
        updatedAt: now,
      },
    ],
    truthFiles: [
      {
        bookId: "book_001",
        fileName: "current_state.md",
        category: "运行态",
        note: "角色位置和阵纹状态需校正。",
        content: "# current_state\n\n- 主角位于断崖外缘\n- 师父未公开旧宗门关系\n- 阵纹触发时序待修正",
        createdAt: now,
        updatedAt: now,
      },
      {
        bookId: "book_001",
        fileName: "story_bible.md",
        category: "世界观",
        note: "卷二宗门法统规则已冻结。",
        content: "# story_bible\n\n- 旧宗门复辟派以法统复位为名行动\n- 断崖遗址是卷二争夺焦点",
        createdAt: now,
        updatedAt: now,
      },
      {
        bookId: "book_002",
        fileName: "current_state.md",
        category: "运行态",
        note: "暂无 drift。",
        content: "# current_state\n\n- 主角仍在熔炉试台\n- 竞争对手尚未正式入场",
        createdAt: now,
        updatedAt: now,
      },
    ],
    resources: [
      {
        refId: "res_audit_001",
        type: "text",
        uri: "/api/v1/resources/res_audit_001",
        content: "审计详情：第12章人物位置和阵纹触发时序冲突，建议把师父提前到达断崖的时间向后平移半章。",
        createdAt: now,
      },
    ],
  };
}
